CREATE DATABASE ClinicaDB;
GO
USE ClinicaDB;
GO


CREATE TABLE Rol (
RoleId INT IDENTITY PRIMARY KEY,
Name NVARCHAR(50) NOT NULL UNIQUE
);


CREATE TABLE Usuario (
UserId INT IDENTITY PRIMARY KEY,
Username NVARCHAR(50) NOT NULL UNIQUE,
Email NVARCHAR(100) NOT NULL UNIQUE,
PasswordHash VARBINARY(256) NOT NULL,
PasswordSalt VARBINARY(128) NOT NULL,
IsActive BIT NOT NULL DEFAULT 1,
CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);


CREATE TABLE UsuarioRol (
UserId INT NOT NULL,
RoleId INT NOT NULL,
PRIMARY KEY(UserId, RoleId),
FOREIGN KEY(UserId) REFERENCES Usuario(UserId),
FOREIGN KEY(RoleId) REFERENCES Rol(RoleId)
);


CREATE TABLE Paciente (
PacienteId INT IDENTITY PRIMARY KEY,
UserId INT NULL,
Cedula NVARCHAR(20) NOT NULL UNIQUE,
Nombre NVARCHAR(60) NOT NULL,
Apellidos NVARCHAR(80) NOT NULL,
Telefono NVARCHAR(20) NULL,
FechaNacimiento DATE NULL,
FOREIGN KEY(UserId) REFERENCES Usuario(UserId)
);


CREATE TABLE Doctor (
DoctorId INT IDENTITY PRIMARY KEY,
Nombre NVARCHAR(60) NOT NULL,
Apellidos NVARCHAR(80) NOT NULL,
Especialidad NVARCHAR(100) NOT NULL,
Telefono NVARCHAR(20) NULL
);


CREATE TABLE Cita (
CitaId INT IDENTITY PRIMARY KEY,
PacienteId INT NOT NULL,
DoctorId INT NOT NULL,
FechaHora DATETIME2 NOT NULL,
Estado NVARCHAR(20) NOT NULL DEFAULT 'Programada',
Observaciones NVARCHAR(400) NULL,
CONSTRAINT UQ_Cita_Doctor_Fecha UNIQUE (DoctorId, FechaHora),
FOREIGN KEY(PacienteId) REFERENCES Paciente(PacienteId),
FOREIGN KEY(DoctorId) REFERENCES Doctor(DoctorId)
);


CREATE TABLE DoctorHorario (
HorarioId INT IDENTITY PRIMARY KEY,
DoctorId INT NOT NULL,
DiaSemana TINYINT NOT NULL CHECK (DiaSemana BETWEEN 1 AND 7),
HoraInicio TIME NOT NULL,
HoraFin TIME NOT NULL,
FOREIGN KEY(DoctorId) REFERENCES Doctor(DoctorId)
);